version:  "3.7"

services:
  backend:
    image: "node:18"
    container_name: "backend"
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: "node index.js"
  frontend:
    image: "node:18"
    container_name: "frontend"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: "npm start"
    depends_on:
      - backend